import { Project, User, RoadmapFeature, SkillCategory, MatchedTeam, Mentor, UserSettings } from './types';

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: 'frontend',
    name: 'Frontend & UI',
    skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Vue.js', 'Framer Motion'],
  },
  {
    id: 'backend',
    name: 'Backend & Systems',
    skills: ['Node.js', 'Python', 'Go', 'PostgreSQL', 'FastAPI', 'Supabase', 'GraphQL'],
  },
  {
    id: 'aiml',
    name: 'AI & Machine Learning',
    skills: ['PyTorch', 'LangChain', 'OpenAI / LLMs', 'Computer Vision', 'NLP', 'TensorFlow'],
  },
  {
    id: 'design',
    name: 'Product & Design',
    skills: ['Figma', 'UI/UX Design', 'Design Systems', 'User Research', '3D / Spline'],
  },
  {
    id: 'devops',
    name: 'DevOps & Mobile',
    skills: ['Docker', 'Kubernetes', 'AWS', 'React Native', 'Swift', 'CI/CD'],
  },
];

export const MOCK_MENTORS: User[] = [
  {
    id: 'mentor-1',
    name: 'Dr. Neha Verma',
    email: 'neha.verma@cropsight.ai',
    role: 'mentor',
    skills: ['Python', 'Computer Vision', 'Agriculture Tech', 'AI/ML'],
    expertise_tags: ['Computer Vision', 'Agriculture Tech', 'AI/ML'],
    experience_level: 'lead',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    bio: 'Senior AI Researcher @ CropSight.AI. Specializes in remote sensing, computer vision and AI solutions for agriculture.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mentor-2',
    name: 'Aarav Mehta',
    email: 'aarav@neuralflow.io',
    role: 'mentor',
    skills: ['PyTorch', 'OpenAI / LLMs', 'FastAPI'],
    expertise_tags: ['PyTorch', 'LLMs', 'Model Optimization'],
    experience_level: 'lead',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    bio: 'Principal ML Engineer building low-latency inference pipelines.',
    created_at: new Date().toISOString(),
  },
];

export const MOCK_PARTICIPANTS: User[] = [
  {
    id: 'user-101',
    name: 'Alex Rivera',
    email: 'alex.r@dev.io',
    role: 'participant',
    skills: ['React', 'Next.js', 'Tailwind CSS', 'TypeScript'],
    expertise_tags: ['Frontend'],
    experience_level: 'intermediate',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    bio: 'Passionate UI engineer building responsive web experiences.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'user-102',
    name: 'Sophia Chen',
    email: 'sophia.c@ml.org',
    role: 'participant',
    skills: ['Python', 'PyTorch', 'OpenAI / LLMs', 'LangChain'],
    expertise_tags: ['AI/ML'],
    experience_level: 'advanced',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    bio: 'AI researcher focused on vector databases and multi-agent coordination.',
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_USER_SETTINGS: UserSettings = {
  fullName: 'Varun Khandelwal',
  email: 'varun.khandelwal@example.com',
  bio: 'AI enthusiast | Building the future, one hack at a time.',
  role: 'judge',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  notifications: {
    emailNotifications: true,
    mentorRequests: true,
    teamUpdates: true,
    systemAnnouncements: false,
  },
  connectedAccounts: {
    github: true,
    google: true,
    linkedin: false,
    discord: false,
  },
};

export const MOCK_MENTORS_LIST: Mentor[] = [
  {
    id: 'mentor-10',
    name: 'Dr. Neha Verma',
    title: 'Senior AI Researcher',
    company: 'CropSight.AI',
    status: 'Open',
    tags: ['Computer Vision', 'Agriculture Tech', 'AI/ML'],
    experience_years: 8,
    about: 'Specializes in remote sensing, computer vision and AI solutions for agriculture. Mentored 40+ hackathon teams and startups.',
    sessions_completed: 128,
    avg_rating: 4.9,
    response_time: '~2 hrs',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'mentor-11',
    name: 'Aarav Mehta',
    title: 'Principal ML Engineer',
    company: 'NeuralFlow',
    status: 'Open',
    tags: ['PyTorch', 'LLMs', 'Model Optimization'],
    experience_years: 6,
    about: 'Building low-latency inference pipelines for vision and language models. Passionate about helping teams deploy models fast.',
    sessions_completed: 94,
    avg_rating: 4.8,
    response_time: '~1 hr',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'mentor-12',
    name: 'Sophia Lin',
    title: 'Staff Frontend Architect',
    company: 'DesignOps.io',
    status: 'Open',
    tags: ['React', 'Next.js', 'UI/UX Design'],
    experience_years: 7,
    about: 'Expert in design systems, micro-animations, and responsive fullstack web apps.',
    sessions_completed: 112,
    avg_rating: 5.0,
    response_time: '~30 mins',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'mentor-13',
    name: 'Kunal Deshmukh',
    title: 'Cloud Infrastructure Lead',
    company: 'ScaleGrid',
    status: 'Busy',
    tags: ['PostgreSQL', 'Docker', 'FastAPI'],
    experience_years: 10,
    about: 'Specialist in high-concurrency database design, serverless deployments, and system security.',
    sessions_completed: 86,
    avg_rating: 4.9,
    response_time: '~3 hrs',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-ecoverse',
    team_id: 'team-greenmatter',
    team_name: 'Team GreenMatter',
    title: 'EcoVerse AI',
    tag_line: 'AI-driven environmental monitoring solution using satellite data and predictive analytics.',
    repo_url: 'https://github.com/greenmatter/ecoverse-ai',
    readme_text: `# EcoVerse AI
AI-driven environmental monitoring solution using satellite data and predictive analytics. EcoVerse fuses Sentinel-2 imagery with local IoT sensor data to forecast deforestation risks and carbon absorption rates in real time.

## Tech Stack
- Python, TensorFlow, React, PostgreSQL
- FastAPI inference server for satellite image segmentation
- Recharts animated telemetry dashboard for land decay rate

## Features
- Real-time satellite imagery fusion
- Automated anomaly detection for illegal logging & deforestation
- Predictive yield models for sustainable agriculture`,
    file_tree: `root/
├── ml/
│   ├── satellite_segmentation.py
│   ├── model.onnx
│   └── data_pipeline.py
├── frontend/
│   ├── src/components/RadarAnalytics.tsx
│   └── src/App.tsx
├── backend/
│   ├── api/routes.py
│   └── main.py
├── package.json
└── README.md`,
    submitted_at: '21 May, 2025 10:24 AM',
    tags: ['AIML', 'Python', 'TensorFlow', 'React', 'PostgreSQL'],
    category: 'AI for Good',
    team_size: 4,
    badge: 'Finalist',
    cover_image: 'https://images.unsplash.com/photo-1511497584788-876761465586?w=600&auto=format&fit=crop&q=80',
    evaluation: {
      id: 'eval-ecoverse',
      project_id: 'proj-ecoverse',
      overall_score: 8.28,
      scores: {
        innovation: 8.8,
        technical: 8.3,
        completeness: 7.9,
        ux: 8.1,
      },
      score_breakdown: {
        innovation: { score: 8.8, maxScore: 10, explanation: 'Unique idea with strong real-world impact.' },
        technical: { score: 8.3, maxScore: 10, explanation: 'Well-architected with advanced tech stack.' },
        completeness: { score: 7.9, maxScore: 10, explanation: 'Most features implemented. Testing could be stronger.' },
        ux: { score: 8.1, maxScore: 10, explanation: 'Clean UI and smooth user experience.' },
      },
      feedback: 'EcoVerse AI demonstrates strong potential with its innovative approach to environmental monitoring using multi-source data fusion and AI. The technical implementation is solid and scalable. Focus on improving test coverage and adding more visual explanations for non-technical users to enhance impact.',
      recommendations: [
        'Add more real-time data streams for better accuracy.',
        'Improve documentation and API references.',
        'Consider a mobile-first experience for field users.',
      ],
      created_at: '2025-05-21T10:30:00Z',
    },
  },
  {
    id: 'proj-medbot',
    team_id: 'team-medvangers',
    team_name: 'Team MedVangers',
    title: 'MedBot Pro',
    tag_line: 'Real-time AI diagnostic copilot for ICU patient vitals triage and drug interaction alerts.',
    repo_url: 'https://github.com/medvangers/medbot-pro',
    readme_text: '# MedBot Pro\nReal-time diagnostic copilot analyzing continuous telemetry and electronic health records to prevent critical drug contraindications.',
    file_tree: 'root/\n├── src/triage.py\n├── app/page.tsx',
    submitted_at: '21 May, 2025 09:15 AM',
    tags: ['Healthcare', 'PyTorch', 'FastAPI', 'Next.js'],
    category: 'Healthcare',
    team_size: 4,
    badge: 'Top 5',
    cover_image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80',
    evaluation: {
      id: 'eval-medbot',
      project_id: 'proj-medbot',
      overall_score: 8.1,
      scores: {
        innovation: 8.5,
        technical: 8.2,
        completeness: 7.8,
        ux: 7.9,
      },
      score_breakdown: {
        innovation: { score: 8.5, maxScore: 10, explanation: 'High clinical utility for ICU triage.' },
        technical: { score: 8.2, maxScore: 10, explanation: 'Robust PyTorch & FastAPI streaming core.' },
        completeness: { score: 7.8, maxScore: 10, explanation: 'Core telemetry works; edge alerts in progress.' },
        ux: { score: 7.9, maxScore: 10, explanation: 'Intuitive dark mode dashboard for medical personnel.' },
      },
      feedback: 'MedBot Pro provides critical real-time alerts for medical staff. The architecture scales cleanly under high socket throughput.',
      recommendations: ['Conduct clinical synthetic data validation.', 'Add offline fallback storage.'],
      created_at: '2025-05-21T09:40:00Z',
    },
  },
  {
    id: 'proj-learnloop',
    team_id: 'team-codecrafters',
    team_name: 'Team CodeCrafters',
    title: 'LearnLoop',
    tag_line: 'Adaptive AI tutor personalizing coding curriculum through interactive micro-debugging quizzes.',
    repo_url: 'https://github.com/codecrafters/learnloop',
    readme_text: '# LearnLoop\nAdaptive coding platform using LLM agent feedback loop.',
    file_tree: 'root/\n├── app/tutor/page.tsx',
    submitted_at: '21 May, 2025 08:30 AM',
    tags: ['EdTech', 'React', 'Node.js', 'Tailwind', 'Supabase'],
    category: 'EdTech',
    team_size: 3,
    cover_image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80',
    evaluation: {
      id: 'eval-learnloop',
      project_id: 'proj-learnloop',
      overall_score: 7.4,
      scores: {
        innovation: 7.6,
        technical: 7.3,
        completeness: 7.2,
        ux: 7.5,
      },
      feedback: 'Great user flow and adaptive quiz generator. Solid foundation for student learning.',
      recommendations: ['Add code execution sandbox.', 'Integrate peer pairing.'],
      created_at: '2025-05-21T08:50:00Z',
    },
  },
  {
    id: 'proj-agrisense',
    team_id: 'team-agronexus',
    team_name: 'Team AgroNexus',
    title: 'AgriSense',
    tag_line: 'Computer vision crop health scanner detecting fungal infections via farmer mobile photos.',
    repo_url: 'https://github.com/agronexus/agrisense',
    readme_text: '# AgriSense\nComputer vision crop health scanner for smallholder farmers.',
    file_tree: 'root/\n├── cv/detector.py',
    submitted_at: '20 May, 2025 11:00 PM',
    tags: ['Agritech', 'Python', 'OpenCV', 'FastAPI'],
    category: 'Agritech',
    team_size: 4,
    cover_image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&auto=format&fit=crop&q=80',
    evaluation: {
      id: 'eval-agrisense',
      project_id: 'proj-agrisense',
      overall_score: 7.0,
      scores: {
        innovation: 7.2,
        technical: 7.1,
        completeness: 6.8,
        ux: 6.9,
      },
      feedback: 'Practical agricultural utility with lightweight computer vision model running fast on mobile.',
      recommendations: ['Expand crop disease dataset.', 'Provide local language translation.'],
      created_at: '2025-05-20T11:30:00Z',
    },
  },
  {
    id: 'proj-finsage',
    team_id: 'team-fractalfalcons',
    team_name: 'Team Fractal Falcons',
    title: 'FinSage',
    tag_line: 'AI financial advisor performing automated portfolio stress-testing against macroeconomic shocks.',
    repo_url: 'https://github.com/fractalfalcons/finsage',
    readme_text: '# FinSage\nAI automated financial stress testing engine.',
    file_tree: 'root/\n├── main.go',
    submitted_at: '20 May, 2025 09:30 PM',
    tags: ['FinTech', 'Go', 'React', 'PostgreSQL', 'AI/ML'],
    category: 'FinTech',
    team_size: 4,
    cover_image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&auto=format&fit=crop&q=80',
    evaluation: {
      id: 'eval-finsage',
      project_id: 'proj-finsage',
      overall_score: 6.5,
      scores: {
        innovation: 6.8,
        technical: 6.7,
        completeness: 6.3,
        ux: 6.2,
      },
      feedback: 'Good backtesting framework in Go, UI needs further refinement for complex asset graphs.',
      recommendations: ['Simplify chart legends.', 'Add export options for PDF compliance reports.'],
      created_at: '2025-05-20T10:00:00Z',
    },
  },
  {
    id: 'proj-travelgenie',
    team_id: 'team-wanderers',
    team_name: 'Team Wanderers',
    title: 'TravelGenie',
    tag_line: 'Hyper-personalized itinerary engine dynamically adjusting paths according to live crowd density.',
    repo_url: 'https://github.com/wanderers/travelgenie',
    readme_text: '# TravelGenie\nDynamic crowd-aware travel planner.',
    file_tree: 'root/\n├── app/planner/page.tsx',
    submitted_at: '20 May, 2025 07:15 PM',
    tags: ['Travel', 'Next.js', 'OpenAI', 'Supabase', 'Tailwind'],
    category: 'Travel',
    team_size: 3,
    cover_image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=600&auto=format&fit=crop&q=80',
    evaluation: {
      id: 'eval-travelgenie',
      project_id: 'proj-travelgenie',
      overall_score: 6.2,
      scores: {
        innovation: 6.4,
        technical: 6.0,
        completeness: 6.2,
        ux: 6.2,
      },
      feedback: 'Clean mobile-friendly UI. Itinerary generation is fast and responds well to budget constraints.',
      recommendations: ['Integrate real-time transit APIs.', 'Support multi-destination group trip polls.'],
      created_at: '2025-05-20T07:45:00Z',
    },
  },
  {
    id: 'proj-aidchain',
    team_id: 'team-chainguardians',
    team_name: 'Team ChainGuardians',
    title: 'AidChain',
    tag_line: 'Transparent disaster relief distribution tracking via verifiable smart contracts & geo-stamps.',
    repo_url: 'https://github.com/chainguardians/aidchain',
    readme_text: '# AidChain\nTransparent disaster relief distribution ledger.',
    file_tree: 'root/\n├── contracts/AidRelief.sol',
    submitted_at: '20 May, 2025 05:00 PM',
    tags: ['Blockchain', 'Solidity', 'Next.js', 'Web3.js', 'Ethers'],
    category: 'Blockchain',
    team_size: 3,
    cover_image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&auto=format&fit=crop&q=80',
    evaluation: {
      id: 'eval-aidchain',
      project_id: 'proj-aidchain',
      overall_score: 6.0,
      scores: {
        innovation: 6.3,
        technical: 6.0,
        completeness: 5.8,
        ux: 5.9,
      },
      feedback: 'Solid smart contract verification flow, gas optimization needed for bulk supply disbursements.',
      recommendations: ['Implement Layer 2 rollups for lower transaction fees.', 'Simplify wallet onboarding.'],
      created_at: '2025-05-20T05:30:00Z',
    },
  },
  {
    id: 'proj-skillbridge',
    team_id: 'team-bitbuilders',
    team_name: 'Team BitBuilders',
    title: 'SkillBridge',
    tag_line: 'Peer-to-peer mentorship matrix connecting underrepresented developers with industry coaches.',
    repo_url: 'https://github.com/bitbuilders/skillbridge',
    readme_text: '# SkillBridge\nPeer mentorship matrix platform.',
    file_tree: 'root/\n├── src/index.ts',
    submitted_at: '20 May, 2025 03:20 PM',
    tags: ['Social Impact', 'React', 'Node.js', 'GraphQL', 'MongoDB'],
    category: 'Social Impact',
    team_size: 4,
    cover_image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
    evaluation: {
      id: 'eval-skillbridge',
      project_id: 'proj-skillbridge',
      overall_score: 5.8,
      scores: {
        innovation: 6.0,
        technical: 5.6,
        completeness: 5.8,
        ux: 5.8,
      },
      feedback: 'Great social vision and intuitive pairing form. Needs backend stability fixes under load.',
      recommendations: ['Add automated calendar scheduling integration.', 'Include video call webhooks.'],
      created_at: '2025-05-20T03:50:00Z',
    },
  },
];

export const MOCK_MATCHED_TEAMS: MatchedTeam[] = [
  {
    id: 'team-nova',
    name: 'Team Nova',
    matchScore: 92,
    badge: 'Best Match',
    members: [
      { name: 'Aaron Mehta', role: 'ML Engineer', avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80' },
      { name: 'Riya Sharma', role: 'Frontend Dev', avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80' },
      { name: 'Kunal Verma', role: 'Backend Dev', avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80' },
      { name: 'Diya Patel', role: 'UI/UX Designer', avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80' },
    ],
    skillBreakdown: {
      design: 25,
      frontend: 30,
      backend: 25,
      ml: 20,
    },
  },
  {
    id: 'team-codecrafters-match',
    name: 'CodeCrafters',
    matchScore: 89,
    members: [
      { name: 'Siddharth', role: 'Data Scientist', avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80' },
      { name: 'Megha Iyer', role: 'Frontend Dev', avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100&auto=format&fit=crop&q=80' },
      { name: 'Arjun Nair', role: 'DevOps', avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80' },
      { name: 'Sneha Reddy', role: 'ML Engineer', avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80' },
    ],
    skillBreakdown: {
      design: 20,
      frontend: 35,
      backend: 25,
      ml: 20,
    },
  },
  {
    id: 'team-bytebuilders-match',
    name: 'Byte Builders',
    matchScore: 89,
    members: [
      { name: 'Vivan Singh', role: 'TensorFlow', avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&auto=format&fit=crop&q=80' },
      { name: 'Ananya Joshi', role: 'Figma', avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=100&auto=format&fit=crop&q=80' },
      { name: 'Yash Des', role: 'Go', avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80' },
      { name: 'Sneha', role: 'Backend Dev', avatar_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&auto=format&fit=crop&q=80' },
    ],
    skillBreakdown: {
      design: 25,
      frontend: 25,
      backend: 30,
      ml: 20,
    },
  },
];

export const MOCK_ROADMAP_FEATURES: RoadmapFeature[] = [
  {
    id: 'feat-1',
    name: 'Automated Repository Parsing',
    description: 'Ingests GitHub repos, parses READMEs and code structure to extract core features and tech stack automatically.',
    tier: 1,
    category: 'AI Evaluation',
    icon_name: 'Code2',
  },
  {
    id: 'feat-2',
    name: 'Radar Chart Rubric Scoring',
    description: 'Evaluates projects across Innovation, Technical Complexity, Completeness, and UX with standardized 1-10 scores.',
    tier: 1,
    category: 'AI Evaluation',
    icon_name: 'Shield',
  },
  {
    id: 'feat-3',
    name: 'Skill Complementarity Matrix',
    description: 'Matches participants into balanced teams based on missing skills rather than raw skill overlap.',
    tier: 1,
    category: 'Team Formation',
    icon_name: 'Users',
  },
  {
    id: 'feat-4',
    name: 'Instant AI Mentor Assistant',
    description: 'First-pass AI code blocker triage with automatic routing to human mentors when needed.',
    tier: 1,
    category: 'Mentorship',
    icon_name: 'MessageSquare',
  },
  {
    id: 'feat-5',
    name: 'Live Judging Leaderboard',
    description: 'Real-time aggregation of judge scores with bias detection and outlier normalization.',
    tier: 2,
    category: 'Judging Operations',
    icon_name: 'Trophy',
  },
  {
    id: 'feat-6',
    name: 'Sponsor Prize Matching',
    description: 'Automated analysis of project repos against sponsor prize criteria and API usage requirements.',
    tier: 2,
    category: 'Sponsors',
    icon_name: 'Sparkles',
  },
];

export const ROADMAP_FEATURES = MOCK_ROADMAP_FEATURES;
